### ISSUE TITLE
This addon blocks other addons (Icinga Status)

### ISSUE THREAD

**Issue by michabbb** [snytkine/staying_alive#4]
hi,
i really love this addon, but problem is, it blocks another important addon i´m using:

https://chrome.google.com/webstore/detail/icinga-status/imaieifkljkcdepgaeommbdgihollphm

i don´t know where the problem is, but the icinga addon is unable to load the data when staying alive is active.

i am not able to debug this, please help!

btw... i don´t understand that this is even possible in chrome... ;-((

thx

**Comment by michabbb** [comment]
help... i need somebody help... lalala.... ;)

**Comment by snytkine** [comment]
what extension is it blocking? The staying alive intercepts network
requests and for foreground requests in inserts a small piece of javascript
into pages but this javascript is not executed unless the domain is
configured to do so. Also the code of this extension is open-sourced and
can be viewed by anyone - it's on github.

On Wed, Mar 12, 2014 at 9:08 AM, Michael Bladowski <notifications@github.com

**Comment by michabbb** [comment]
wow, finally a "do it youself, dickhead" posting, great! i want to help and thats why i informed you both, the developer of extension one and the developer of extension two... if you don´t care, so what... never mind... i will use extensions they don´t interfere with each other! so, not yours anymore,
even i like it very much ;(
for some developers open-source always means: if you have a problem, do it yourself!
great attitude...

**Comment by snytkine** [comment]
Thank you for your help, but can you be more specific as to what extension
its interfering with?

On Wed, Mar 12, 2014 at 9:38 AM, Michael Bladowski <notifications@github.com

**Comment by michabbb** [comment]
i don´t really know if you are kidding me or not ? ;) please take a look to the first posting of this topic...

**Comment by michabbb** [comment]
thanks for _not_ reading, the issue can be closed --> https://github.com/kepi/IcingaChromedStatus/issues/21#issuecomment-37604415
